BEGIN TRANSACTION;
INSERT INTO "Locations" VALUES (1,'MineHead',3,10,1);
INSERT INTO "Locations" VALUES (2,'Dunster',1,20,1);
INSERT INTO "Locations" VALUES (3,'Blue Anchor',2,30,1);
INSERT INTO "Locations" VALUES (4,'Washford',2,40,1);
INSERT INTO "Locations" VALUES (5,'Watchet',2,50,1);
INSERT INTO "Locations" VALUES (6,'Doniford',1,60,1);
INSERT INTO "Locations" VALUES (7,'Williton',2,70,1);
INSERT INTO "Locations" VALUES (8,'Stogumber',1,80,1);
INSERT INTO "Locations" VALUES (9,'Crowcombe Heathfield',2,90,1);
INSERT INTO "Locations" VALUES (10,'Bishops Lydeard',2,100,1);
INSERT INTO "Locations" VALUES (11,'Norton Fitzwarren',1,110,1);
INSERT INTO "Routes" VALUES (1,'West Somerset Railway','WSR','Heritage railway in the UK');
INSERT INTO "Branches" VALUES (0,'MainLine','WSR-M','Main branch for passenger traffic',1);
INSERT INTO "Branches" VALUES (2,'FitzWarren Connection','WSR-FW','Connection from Bishop Lydeard  to FitzWarren',1);
INSERT INTO "Services" VALUES (1,'To BL, class 47, B set','A47B1','passenger','From Minehead to Bishops Lydeard all stops 1',97,1);
INSERT INTO "Services" VALUES (2,'To MH, cl47, set A, 1','B47A1','passenger','From Bishop Lydeard to Minehead, class 47, all stops',94,1);
INSERT INTO "TimeEvents" VALUES (1,'D',0,1,1);
INSERT INTO "TimeEvents" VALUES (2,'D',9,2,1);
INSERT INTO "TimeEvents" VALUES (3,'A',6,3,1);
INSERT INTO "TimeEvents" VALUES (4,'D',1,3,1);
INSERT INTO "TimeEvents" VALUES (5,'D',8,4,1);
INSERT INTO "TimeEvents" VALUES (6,'D',10,5,1);
INSERT INTO "TimeEvents" VALUES (7,'D',4,6,1);
INSERT INTO "TimeEvents" VALUES (8,'A',4,7,1);
INSERT INTO "TimeEvents" VALUES (9,'D',1,7,1);
INSERT INTO "TimeEvents" VALUES (10,'D',11,8,1);
INSERT INTO "TimeEvents" VALUES (11,'A',7,9,1);
INSERT INTO "TimeEvents" VALUES (12,'D',4,9,1);
INSERT INTO "TimeEvents" VALUES (13,'A',12,10,1);
INSERT INTO "TimeEvents" VALUES (14,'D',0,10,2);
INSERT INTO "TimeEvents" VALUES (15,'A',12,9,2);
INSERT INTO "TimeEvents" VALUES (16,'S',2,9,2);
INSERT INTO "TimeEvents" VALUES (17,'D',8,8,2);
INSERT INTO "TimeEvents" VALUES (18,'A',9,7,2);
INSERT INTO "TimeEvents" VALUES (19,'D',11,7,2);
INSERT INTO "TimeEvents" VALUES (20,'D',5,6,2);
INSERT INTO "TimeEvents" VALUES (21,'D',4,5,2);
INSERT INTO "TimeEvents" VALUES (22,'D',9,4,2);
INSERT INTO "TimeEvents" VALUES (23,'A',7,3,2);
INSERT INTO "TimeEvents" VALUES (24,'D',1,3,2);
INSERT INTO "TimeEvents" VALUES (25,'D',8,2,2);
INSERT INTO "TimeEvents" VALUES (26,'A',8,1,2);
INSERT INTO "TimeTables" VALUES (1,'WSR Service mode','WSR1','TSW Service mode timetable',1);
COMMIT;
